sudo: false

language: go

go:
  - '1.12.x'

notifications:
  email: false

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules

services:
  - 'docker'

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.19.1/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

jobs:
  include:
    - stage: docs build
      if: type != pull_request
      script:
        - sh build/bin/trigger-docs-travis $TRAVIS_API_TOKEN
    - stage: test
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/bin/push-images; fi'

deploy:
  provider: script
  script: VERSION=$TRAVIS_TAG ./build/bin/push-images
  on:
    tags: true
    all_branches: true
